name: Build & Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Create SFML directory
      run: mkdir -p build/sfml
    - name: Checkout SFML 2.6.x branch
      uses: actions/checkout@v3
      with:
        repository: SFML/SFML
        ref: 2.6.x
        path: build/sfml
    - name: Configure, Build & Install SFML
      run: >
        cmake -Sbuild/sfml -Bbuild/sfml/build &&
        cmake --build build/sfml/build &&
        cmake --install build/sfml/build --config Debug
    - name: Install clang-tidy & dependencies
      run: sudo apt install clang-tidy libglm-dev
    - name: Configure
      run: cmake --preset=ci
    - name: Build & Lint
      run: cmake --build build -j 2

